/*=========================================================
REVENUE KPIs
=========================================================*/

-----------------------------------------------------------
-- KPI 1 : Total Revenue
-----------------------------------------------------------
-- Business KPI:
-- What is the total revenue generated by the platform?
--
-- Insight:
-- Measures overall business performance.

SELECT
    ROUND(SUM(order_value),2) AS total_revenue
FROM orders;


-----------------------------------------------------------
-- KPI 2 : Average Order Value
-----------------------------------------------------------
-- Business KPI:
-- How much does an average customer spend per order?
--
-- Insight:
-- Helps understand customer spending behavior.

SELECT
    ROUND(AVG(order_value),2) AS average_order_value
FROM orders;


-----------------------------------------------------------
-- KPI 3 : Highest Order Value
-----------------------------------------------------------
-- Business KPI:
-- What is the highest order value recorded?
--
-- Insight:
-- Identifies premium purchases.

SELECT
    MAX(order_value) AS highest_order_value
FROM orders;


-----------------------------------------------------------
-- KPI 4 : Lowest Order Value
-----------------------------------------------------------
-- Business KPI:
-- What is the lowest order value recorded?
--
-- Insight:
-- Helps understand the minimum transaction value.

SELECT
    MIN(order_value) AS lowest_order_value
FROM orders;


-----------------------------------------------------------
-- KPI 5 : Average Delivery Fee
-----------------------------------------------------------
-- Business KPI:
-- What is the average delivery fee charged?
--
-- Insight:
-- Evaluates delivery pricing strategy.

SELECT
    ROUND(AVG(delivery_fee),2) AS average_delivery_fee
FROM orders;


-----------------------------------------------------------
-- KPI 6 : Total Delivery Fee Collected
-----------------------------------------------------------
-- Business KPI:
-- How much revenue is generated from delivery fees?
--
-- Insight:
-- Measures delivery service income.

SELECT
    ROUND(SUM(delivery_fee),2) AS total_delivery_fee
FROM orders;


-----------------------------------------------------------
-- KPI 7 : Average Discount
-----------------------------------------------------------
-- Business KPI:
-- What is the average discount offered?
--
-- Insight:
-- Helps evaluate promotional campaigns.

SELECT
    ROUND(AVG(discount),2) AS average_discount
FROM orders;


-----------------------------------------------------------
-- KPI 8 : Total Discounts Given
-----------------------------------------------------------
-- Business KPI:
-- What is the total discount provided to customers?
--
-- Insight:
-- Measures promotional spending.

SELECT
    ROUND(SUM(discount),2) AS total_discount
FROM orders;